# -*- coding: utf-8 -*-
"""ClusteringLatsol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fv-X7XRkvJx1W8O0HPrXP0hHpAozukbx
"""

# Import library yang dibutuhkan
import math
import matplotlib.pyplot as plt

# Fungsi untuk menghitung jarak antara dua titik
def hitung_jarak(p1, p2):
    return math.sqrt((p1[0] - p2[0])**2 + (p1[1] - p2[1])**2)

# Fungsi untuk melakukan K-means clustering
def k_means_clustering(data, centers, iterations):
    for _ in range(iterations):
        klaster1 = []
        klaster2 = []

        # Hitung jarak setiap titik data ke kedua titik pusat klaster
        for point in data:
            jarak_C1 = hitung_jarak(point, centers[0])
            jarak_C2 = hitung_jarak(point, centers[1])

            # Tentukan klaster berdasarkan jarak terdekat
            if jarak_C1 < jarak_C2:
                klaster1.append(point)
            else:
                klaster2.append(point)

        # Hitung ulang titik pusat klaster
        centers[0] = (sum(p[0] for p in klaster1) / len(klaster1), sum(p[1] for p in klaster1) / len(klaster1))
        centers[1] = (sum(p[0] for p in klaster2) / len(klaster2), sum(p[1] for p in klaster2) / len(klaster2))

    return klaster1, klaster2, centers

# Titik pusat klaster awal
C1 = (3, 4)
C2 = (6, 4)

# Data titik
data = [(1, 4.5), (3, 6.5), (4, 4.5), (7.5, 3.2), (6, 2.3), (2.5, 3.8), (5, 5.5)]

# Tentukan jumlah iterasi
iterations = 5

# Lakukan K-means clustering
klaster1, klaster2, centers = k_means_clustering(data, [C1, C2], iterations)

# Tampilkan hasil klaster
print("Klaster 1:", klaster1)
print("Klaster 2:", klaster2)

# Visualisasi data
x1 = [point[0] for point in klaster1]
y1 = [point[1] for point in klaster1]

x2 = [point[0] for point in klaster2]
y2 = [point[1] for point in klaster2]

plt.scatter(x1, y1, color='r', label='Klaster 1')
plt.scatter(x2, y2, color='b', label='Klaster 2')
plt.scatter(centers[0][0], centers[0][1], color='g', marker='*', s=200, label='Titik Pusat C1')
plt.scatter(centers[1][0], centers[1][1], color='y', marker='*', s=200, label='Titik Pusat C2')

plt.xlabel('X')
plt.ylabel('Y')
plt.title('K-means Clustering')
plt.legend()
plt.show()